sever:
  port: 8070

spring:
  application:
    name: eureka-server
  config:
    import: "configserver:http://localhost:8071/"
eureka:
  instance:
    hostname: "localhost"
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      default-zone: ${EUREKA_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true